#ifndef PROJECT_MAX17205_TESTER_HPP
#define PROJECT_MAX17205_TESTER_HPP

#include "MAX17205GTestBase.hpp"
#include "project/Components/MAX17205/MAX17205.hpp"

namespace project {

class MAX17205Tester final : public MAX17205GTestBase {
  public:
    // Keep enough history to inspect every transaction and telemetry sample
    // generated by one READ_ALL command.
    static constexpr FwSizeType MAX_HISTORY_SIZE = 100;
    static constexpr FwEnumStoreType TEST_INSTANCE_ID = 0;
    static constexpr FwSizeType TEST_INSTANCE_QUEUE_DEPTH = 10;

    MAX17205Tester();
    ~MAX17205Tester() override;

    void testReadAll();
    void testReset();
    void testReadFailure();

  private:
    // Definitions are generated by UT_AUTO_HELPERS.
    void connectPorts();
    void initComponents();

    // Fake synchronous bus handlers used by the component's output ports.
    Drv::I2cStatus from_busWriteRead_handler(FwIndexType portNum,
                                              U32 address,
                                              Fw::Buffer& writeBuffer,
                          Fw::Buffer& readBuffer) override;
    Drv::I2cStatus from_busWrite_handler(FwIndexType portNum,
                                          U32 address,
                        Fw::Buffer& buffer) override;

    // Return deterministic raw register data for the mocked fuel gauge.
    static U16 valueForRegister(U8 address, U8 reg);

    MAX17205 component;
    // Allows tests to inject a bus failure without hardware.
    Drv::I2cStatus m_nextReadStatus = Drv::I2cStatus::I2C_OK;
    U32 m_readCount = 0;
    U32 m_writeCount = 0;
};

}  // namespace project

#endif
