// ======================================================================
// \title  MAX17205Tester.hpp
// \brief  Unit test harness for the MAX17205 component.
//
// Stands in for the I2C bus driver so the component can be exercised with no
// hardware. The fake bus answers reads from a fixed register table, records
// every transaction so tests can assert on the exact address and register
// sequence, and can be told to fail specific transactions.
// ======================================================================

#ifndef PROJECT_MAX17205_TESTER_HPP
#define PROJECT_MAX17205_TESTER_HPP

#include "MAX17205GTestBase.hpp"
#include "project/Components/MAX17205/MAX17205.hpp"

namespace project {

class MAX17205Tester final : public MAX17205GTestBase {
  public:
    // One full sample is 15 reads plus 15 telemetry writes. Sized to hold
    // several samples so the throttle test can run without truncating.
    static constexpr FwSizeType MAX_HISTORY_SIZE = 256;
    static constexpr FwEnumStoreType TEST_INSTANCE_ID = 0;
    static constexpr FwSizeType TEST_INSTANCE_QUEUE_DEPTH = 10;

    // The number of register reads one full sample performs.
    static constexpr U32 READS_PER_SAMPLE = 15;

    MAX17205Tester();
    ~MAX17205Tester() override;

    // ----------------------------------------------------------------------
    // Test cases
    // ----------------------------------------------------------------------

    //! A clean READ_ALL reads every register, on the right I2C address, in
    //! the expected order, and publishes every channel correctly scaled.
    void testReadAll();

    //! One bad register must not abort the rest of the snapshot.
    void testReadAllPartialFailure();

    //! The rate group input performs the same sample as READ_ALL, and
    //! produces no command response.
    void testScheduledSample();

    //! RESET emits the CONFIG2 write-only transaction.
    void testReset();

    //! A failed RESET is reported as an event and a failed command.
    void testResetFailure();

    //! configure() redirects both the main and shadow transactions.
    void testConfigureAddresses();

    //! The error event throttles, and a clean sample re-arms it.
    void testErrorThrottle();

    //! A pack below freezing reports a negative temperature end to end.
    void testSubZeroTemperature();

  private:
    // Definitions are generated by UT_AUTO_HELPERS.
    void connectPorts();
    void initComponents();

    // ----------------------------------------------------------------------
    // Fake bus
    // ----------------------------------------------------------------------

    Drv::I2cStatus from_busWriteRead_handler(FwIndexType portNum,
                                             U32 address,
                                             Fw::Buffer& writeBuffer,
                                             Fw::Buffer& readBuffer) override;
    Drv::I2cStatus from_busWrite_handler(FwIndexType portNum, U32 address, Fw::Buffer& buffer) override;

    //! Raw register contents the fake gauge reports, honouring any override.
    U16 valueForRegister(U32 address, U8 reg) const;

    //! Make one register report `value` instead of its table entry, so a test
    //! can drive a specific reading (a sub-zero temperature, say) through the
    //! real byte path rather than calling the decode function directly.
    void overrideRegister(U32 address, U8 reg, U16 value);

    //! Drop any override and go back to the table.
    void clearOverride();

    //! One recorded bus transaction.
    struct Transaction {
        U32 address;
        U8 reg;
    };

    //! Assert that transaction `index` targeted this address and register.
    void assertTransaction(U32 index, U32 address, U8 reg) const;

    //! Check every channel of a clean sample against its expected value.
    void assertCleanSampleTelemetry();

    //! Make every bus transaction fail with this status.
    void failEverything(Drv::I2cStatus status);

    //! Make just this one register fail; everything else succeeds.
    void failOnly(U32 address, U8 reg, Drv::I2cStatus status);

    //! Let every transaction succeed again.
    void failNothing();

    //! Forget recorded transactions and all port history.
    void resetRecording();

    MAX17205 component;

    // Injected-failure configuration.
    Drv::I2cStatus m_forcedStatus = Drv::I2cStatus::I2C_OK;
    bool m_failEverything = false;
    U32 m_failAddress = 0;
    U8 m_failRegister = 0;

    // Single-register value override.
    bool m_overrideActive = false;
    U32 m_overrideAddress = 0;
    U8 m_overrideRegister = 0;
    U16 m_overrideValue = 0;

    // Recorded transactions, oldest first.
    static constexpr U32 MAX_TRANSACTIONS = 64;
    Transaction m_transactions[MAX_TRANSACTIONS] = {};
    U32 m_transactionCount = 0;

    // Payload of the most recent write-only transaction, copied out while the
    // component's buffer is still alive. The Fw::Buffer kept by the generated
    // port history only holds a pointer, and for these transactions it points
    // into a stack frame inside the component that is gone by the time a test
    // body runs -- so the bytes must be captured here, in the handler.
    static constexpr U32 MAX_WRITE_PAYLOAD = 8;
    U8 m_lastWrite[MAX_WRITE_PAYLOAD] = {};
    U32 m_lastWriteSize = 0;
    U32 m_writeCount = 0;
};

}  // namespace project

#endif
